---
title: "map_bars"
author: "Christoffer Kramer"
date: "1/6/2021"
output: html_document
---

```{r}
# Import libs -------------------------------------------------------------
library(tidyverse)
library(tmap)
library(sf)
setwd("src")
```


```{r}
# Read and clean data -----------------------------------------------------
# Read data with population density
pop_sqkm <- read_csv("../data/processed_data/pop_sqkm.csv") 
# Save the column of average density
pop_avg_density <- pop_sqkm %>% select(Kommune, people_pr_sqkm_avg)

# Read data with crime statistics
charged_vs_reported <- read.csv("../data/processed_data/charged_vs_reported_pct.csv")
charged <- read.csv("../data/processed_data/charges_per_10k.csv")
reported <- read.csv("../data/processed_data/reported_per_10k.csv")

#Read the municipalities polygons
municipalities <- readRDS("../data/raw_data/gadm36_DNK_2_sp.rds")
#Read municipalities as a spatial object
municipalities <- st_as_sf(municipalities)
#Give municipaliteis a CRS
municipalities <- st_transform(municipalities, crs = 4326)

#Clean names
municipalities$NAME_2[31] <- "Aarhus"
municipalities$NAME_2[21] <- "Høje-Taastrup"
municipalities$NAME_2[60] <- "Vesthimmerlands"

#Create data layers
#Population density
mun_density <- merge(pop_avg_density, municipalities,
                        by.x = "Kommune", by.y = "NAME_2")
#Reports that leads to charges
mun_charged_vs_reported <- merge(charged_vs_reported, municipalities,
                                 by.x = "Municipalities", by.y = "NAME_2")
# Charges
mun_charged <- merge(charged, municipalities,
                     by.x = "Municipalities", by.y = "NAME_2")
# Reports
mun_reported <- merge(reported, municipalities,
                      by.x = "Municipalities", by.y = "NAME_2")


#Transform layers to spatial objects and give them a crs
mun_density <- st_as_sf(mun_density)
mun_density <- st_transform(mun_density, crs = 4326)
mun_charged_vs_reported <- st_as_sf(mun_charged_vs_reported)
mun_charged_vs_reported <- st_transform(mun_charged_vs_reported, crs = 4326)
mun_charged <- st_as_sf(mun_charged)
mun_charged <- st_transform(mun_charged, crs = 4326)
mun_reported <- st_as_sf(mun_reported)
mun_reported <- st_transform(mun_reported, crs = 4326)
```


```{r}
# Create Tmap -------------------------------------------------------------
tmap_mode(mode = "view")
tm_shape(mun_density) +
  tm_polygons("people_pr_sqkm_avg", style = "quantile",
              id = "Kommune",
              title = "Average people pr. sqkm from 2010-2020",
              popup.format = list()) +
  tm_shape(mun_charged_vs_reported) +
  tm_polygons("X2017", style = "pretty") +
    tm_shape(mun_charged) +
  tm_polygons("X2017", style = "pretty") +
    tm_shape(mun_reported) +
  tm_polygons("X2017", style = "pretty")
#tmap_save(density_map, "../output/density_map.html")
```

```{r}
if (require(dplyr) && require(tidyr)) {
	test <- mun_charged_vs_reported %>% 
		gather(X2010, population, -name, -name_long, -iso_a3, -geometry) %>% 
		mutate(year = as.integer(substr(year, 4, 7)))
	
	tm_shape(metro_long) +
		tm_bubbles("population") +
		tm_facets(by = "year")
}


```

