---
title: "Autocorrelation"
author: "Emil Buus Thomsen"
date: "3/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(spatstat)
library(tmap)

```

## R Markdown



## Including Plots

```{r}
#Population in each municipality (used for calculating ratios)
population <- read.csv("../data/raw_data/clean_pop.csv", encoding = "UTF-8")
#Transform it to long format
population <- gather(population, year, population, X2010:X2020)

population <- population %>% rename(Municipalities = Kommune)


# Amount of reported assaults
reported_assaults <- read_csv("../data/processed_data/reported_per_10k.csv")
#Transform it to long format
reported_assaults <- gather(reported_assaults, year, reported, X2010:X2020)

#Amount of actual charges 
charged_assults <- read.csv("../data/processed_data/charges_per_10k.csv", encoding = "UTF-8")
#Transform it to long format
charged_assults <- gather(charged_assults, year, charged, X2010:X2020)

#Spatial data with municipalities
municipalities <- readRDS("../data/raw_data/gadm36_DNK_2_sp.rds")
#Read municipalities as a spatial object
municipalities <- st_as_sf(municipalities)
#Give municipaliteis a CRS
municipalities <- st_transform(municipalities, crs = 32632)

#Clean names
municipalities$NAME_2[31] <- "Aarhus"
municipalities$NAME_2[21] <- "Høje-Taastrup"
municipalities$NAME_2[60] <- "Vesthimmerlands"

```


```{r}
charged_vs_reported_pct <-read.csv("../data/processed_data/charged_vs_reported_pct.csv", encoding = "UTF-8")

#change to long format
charged_vs_reported_pct <- gather(charged_vs_reported_pct, year, repo_vs_char_pct, X2010:X2020)

```



```{r}
assaults <- left_join(reported_assaults, charged_assults, by= c("year", "Municipalities"))
assaults <- left_join(assaults, population, by= c("year", "Municipalities"))
#Remove rows with NA (this basically means all years from before 2007 and all regions that aren't municipalities)

#This is done since I only have population data from 2010
assaults <- assaults %>% 
  na.omit()

#Merge data with municipalities
assaults <- merge(assaults, municipalities, by.x = "Municipalities",
                                            by.y = "NAME_2")

#assaults <- merge(assaults, charged_vs_reported_pct, by = "Municipalities")

#Remove the X that is in front of years
#assaults <- assaults %>%
  #mutate(year = str_remove(year, "X"))

#Convert string to int in year
#assaults <- assaults %>%
  #mutate(year = as.numeric(year))
```



```{r}
assaults <- left_join(assaults, charged_vs_reported_pct, by.x = "Municipalities", by.y = "Municipalities")

#Remove the X that is in front of years
assaults <- assaults %>%
  mutate(year = str_remove(year, "X"))

#Convert string to int in year
assaults <- assaults %>%
  mutate(year = as.numeric(year))

assaults <- subset(assaults, select = c(Municipalities, year, reported,  charged, repo_vs_char_pct, population, geometry))

#Transforming all Na's to 100 procent as we have devided reported = 0 with 0 which returns a Na result. We  interpret this as there have been no reports or charges which equals a 100% of all reports to have been charged.
 assaults$repo_vs_char_pct[is.na(assaults$repo_vs_char_pct)] <- 100
```



```{r}
#Make assaults a spatial object
assaults <- st_as_sf(assaults)
# Give it the correct crs
assaults <- st_transform(assaults, crs = 32632)
```




```{r}
unique_years = unique(assaults$year)

for (year in unique_years) {
  assaults_year <- assaults %>% 
    filter(year == year)
  
  assaults_year <- st_cast(st_simplify(assaults_year, dTolerance = 250), to = "MULTIPOLYGON")

  #Find neighbours based on queen movement
  nb <- poly2nb(assaults_year$geometry)

  #Get center of each municipality
  centers <- st_coordinates(st_centroid(assaults_year$geometry))
  
  
  
  # Run a Moran on reported cases (as a ratio)
  reported_moran_test <- moran.test(assaults_year$reported, nb2listw(nb, style = "W", zero.policy = TRUE), zero.policy = TRUE)
  
  #Run a monte carlo simulation on reported cases (as a ratio)
  reported_mc <- moran.mc(assaults_year$reported, nb2listw(nb, zero.policy = TRUE), zero.policy = TRUE, 
      nsim = 999)
  
  write(paste0("Autocorrelation for the year", year), file = "../output/reported_autocorrelation.txt", append = TRUE)
  write(toString(reported_moran_test), file = "../output/reported_autocorrelation.txt", append = TRUE)
  write(toString(reported_mc), file = "../output/reported_autocorrelation.txt", append = TRUE)
  write("\n", file = "../output/reported_autocorrelation.txt", append = TRUE)
  
  
  
  
  
  # Run a Moran on reported cases (as a ratio)
  charged_moran_test <- moran.test(assaults_year$charged, nb2listw(nb, style = "W", zero.policy = TRUE), zero.policy = TRUE)
  
  #Run a monte carlo simulation on reported cases (as a ratio)
  charged_mc <- moran.mc(assaults_year$charged, nb2listw(nb, zero.policy = TRUE), zero.policy = TRUE, 
      nsim = 999)
  
  write(paste0("Autocorrelation for the year", year), file = "../output/charged_autocorrelation.txt", append = TRUE)
  write(toString(charged_moran_test), file = "../output/charged_autocorrelation.txt", append = TRUE)
  write(toString(charged_mc), file = "../output/charged_autocorrelation.txt", append = TRUE)
  write("\n", file = "../output/charged_autocorrelation.txt", append = TRUE)
  
  
  
  
  # Run a Moran on reported cases (as a ratio)
  reported_vs_charged_moran_test <-  moran.test(assaults_year$repo_vs_char_pct, nb2listw(nb, style = "W", zero.policy = TRUE), zero.policy = TRUE)
  
  #Run a monte carlo simulation on reported cases (as a ratio)
  reported_vs_charged_mc <- moran.mc(assaults_year$repo_vs_char_pct, nb2listw(nb, zero.policy = TRUE), zero.policy = TRUE, 
      nsim = 999)
  
  write(paste0("Autocorrelation for the year ", year), file = "../output/reported_vs_charged_autocorrelation.txt", append = TRUE)
  write(toString(reported_vs_charged_moran_test), file = "../output/reported_vs_charged_autocorrelation.txt", append = TRUE)
  write(toString(reported_vs_charged_mc), file = "../output/reported_vs_charged_autocorrelation.txt", append = TRUE)
  write("\n", file = "../output/reported_vs_charged_autocorrelation.txt", append = TRUE)
}



```



```{r}
assaults_2017 <- assaults %>% 
  filter(year == 2017)

#Plot rapes in 2017 as a 
tmap_mode(mode = "view")
```


## Map of reported rapes

```{r}
tm_shape(assaults_2017) +
 tm_polygons("reported", style = "quantile",
             id = "Municipalities",
             title = "Sexual assault reports pr. 10.000 inhabitants (2017)")
```



## Map of charged rapes

```{r}
tm_shape(assaults_2017) +
 tm_polygons("charged", style = "quantile",
             id = "Municipalities",
             title = "Sexual assault charges pr. 10.000 inhabitants (2017)")
```


```{r}
tm_shape(assaults_2017) +
 tm_polygons("repo_vs_char_pct", style = "quantile",
             id = "Municipalities",
             title = "Sexual assault reported cases vs. charged i % inhabitants (2017)")
```


## Auto correlation test

```{r}
options(scipen = 999)
library(spdep)
#Simplify spatial object
assaults_2017 <- st_cast(st_simplify(assaults_2017, dTolerance = 250), to = "MULTIPOLYGON")

#Find neighbours based on queen movement
nb <- poly2nb(assaults_2017$geometry)

#Get center of each municipality
centers <- st_coordinates(st_centroid(assaults_2017$geometry))
```


## Reported

```{r}
# Run a Moran on reported cases (as a ratio)
moran.test(assaults_2017$reported, nb2listw(nb, style = "W", zero.policy = TRUE), zero.policy = TRUE)
```

```{r}
#Run a monte carlo simulation on reported cases (as a ratio)
moran.mc(assaults_2017$reported, nb2listw(nb, zero.policy = TRUE), zero.policy = TRUE, 
    nsim = 999)
```
## Charged

```{r}
# Run a Moran on reported cases (as a ratio)
moran.test(assaults_2017$charged, nb2listw(nb, style = "W", zero.policy = TRUE), zero.policy = TRUE)
```



```{r}
#Run a monte carlo simulation on reported cases (as a ratio)
moran.mc(assaults_2017$charged, nb2listw(nb, zero.policy = TRUE), zero.policy = TRUE, 
    nsim = 999)
```

## Reported vs. charged

```{r}
# Run a Moran on reported cases (as a ratio)
moran.test(assaults_2017$repo_vs_char_pct, nb2listw(nb, style = "W", zero.policy = TRUE), zero.policy = TRUE)
```

```{r}
#Run a monte carlo simulation on reported cases (as a ratio)
moran.mc(assaults_2017$repo_vs_char_pct, nb2listw(nb, zero.policy = TRUE), zero.policy = TRUE, 
    nsim = 999)
```



