---
title: "bar_map"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(spatstat)
library(sf)
```

```{r}
#Read the municipalities polygons
municipalities <- readRDS("../data/gadm36_DNK_2_sp.rds")
#Read municipalities as a spatial object
municipalities <- st_as_sf(municipalities)
#Give municipaliteis a CRS
municipalities <- st_transform(municipalities, crs = 4326)

#Clean names
municipalities$NAME_2[31] <- "Aarhus"
municipalities$NAME_2[21] <- "Høje-Taastrup"
municipalities$NAME_2[60] <- "Vesthimmerlands"

bars <- read_csv("../data/bars_coords.csv")
bars
```


```{r}
coordinates_bars <- st_as_sf(x= bars,
                             coords = c("lon", "lat"),
                             crs = 4326)

plot(coordinates_bars)
```




```{r}
library(spatstat)

municipalities$pt_count <- lengths(st_intersects(municipalities$geometry, coordinates_bars))

municipalities$pt_count

coordinates_bars
```

Creating a smaller data frame from municipalities data frame

```{r}
#Transforming the municipalities from an sf data frame to a normal
municipalities_and_bars <- data.frame(municipalities)
#selecting only NAME_2 and pt_count
municipalities_and_bars <- subset(municipalities_and_bars, select = c(NAME_2, pt_count))

#Renaming columns
municipalities_and_bars <- municipalities_and_bars %>% 
  rename(Municipality = NAME_2,
         Bars = pt_count
         )
municipalities_and_bars <- municipalities_and_bars[order(municipalities_and_bars$Municipality),]

#Resetting index
row.names(municipalities_and_bars) <- NULL

#The dataframe now only consists of Municipalities and the bar count
municipalities_and_bars$Municipality
```



```{r}
population <- read.csv("../../data/processed_data/clean_population.csv", encoding = "UTF-16")

population <- population %>% 
  rename(Municipality = kommune)
population

population <- population[order(population$Municipality),]

#Resetting index
row.names(population) <- NULL

population

population$avg_popu <- as.integer(rowMeans(population[2:ncol(population)]))

municipalities_and_bars$Bar_pr_person <- municipalities_and_bars$Bars/population$avg_popu[1:99]*10000
municipalities_and_bars
```




```{r}
library(tmap)
#Plot rapes in 2017 as a 
tmap_mode(mode = "view")

tm_shape(municipalities) +
 tm_polygons("pt_count", style = "jenks",
             id = "NAME_2",
             title = "Bars in DK")
```

